### ISSUE TITLE
name conflicts with /usr/bin/sq -- some alternatives

### ISSUE THREAD

**Issue by stevegt** [neilotoole/sq#100]
Has anyone else run into the naming conflict with the /usr/bin/sq that's shipped with ispell?  (For lurkers -- 'ispell' has been around since the early 70's and tends to be installed today as a backend for many text editors, including both vim and emacs, and is available for all major operating systems, including UNIX, Linux, MacOS, and even DOS/Windows.)

In my own case, I wound up deploying this package as 'seeq' to avoid the conflict.  A slightly shorter name that I don't like as much is 'siq'.  Neither of those come up in the output of `apt-file search bin/siq`, `apt-file search bin/seeq`, or googling for `man siq` or `man seeq`.

**Comment by neilotoole** [comment]
@stevegt Apologies for having neglected to respond to this issue. I hear what you're saying re the `sq` name conflicting... and I honestly didn't know about the `ispell` binary from back in the day. But at this stage there's too much stuff out there already depending on the `sq` name.

**Comment by stevegt** [comment]
@neilotoole Thanks for answering.  I'm not sure that's the right conclusion.  What stuff depends on your version of sq?  Is it primarily things you own or control personally, such as the sq.io domain name?

There are millions of installs of ispell out there.  It's reasonable to expect that either you're going to break a lot of machines or your package will not enjoy much adoption.  The latter would be sad, because it really is a good package.

As of this writing, you've got 419 stars and 9 forks -- it will be easier to fix this before those numbers tick higher.

**Comment by stevegt** [comment]
...thinking.  If you do decide to stick with `sq`, it might be best to include a mention in the README that it conflicts with an internal command in the ispell package, and that installing as e.g. `seeq` will avoid conflicts.  Because `sq` is an internal command, not usually called directly by users, the breakage users will see will be hard to track down otherwise.

**Comment by neilotoole** [comment]
@stevegt That's a very good idea.

> the breakage users will see will be hard to track down otherwise.

Do you recall what error/state you experienced? E.g. "if when using ispell, you see X error, this is probably because of a conflict with the ispell's internal `sq` command.". What's the "X error" that you saw, and I'll include it in the readme.

Thank you for your thoughtfulness and insight about all this. It's much appreciated.
