### ISSUE TITLE
feat: allow connection to custom schema in postgres

### ISSUE THREAD

**Issue by c-nv-s** [neilotoole/sq#142]
sq, by default, successfully displays all tables under the default "public" schema/namespace. e.g. ``public.my_table``
it would be useful to allow/show some way to connect to a table with a custom schema in postgres e.g. ``customer1.my_table``

**Comment by neilotoole** [comment]
I've added some docs for this: https://sq.io/docs/drivers/postgres/#non-default-schema

TLDR: Use the `search_path` param when adding the data source.

```shell
sq add 'postgres://sakila:p_ssW0rd@localhost/sakila?search_path=customer'
```
