### ISSUE TITLE
sq fails to detect sqlite fts5 virtual table

### ISSUE THREAD

**Issue by Dialga** [neilotoole/sq#279]
Follow up of #232 
Currently using sq with a sqlite database that has a virtual table, sq fails with an error:
```
sq: SQL query against @db failed: SELECT * FROM "a": no such module: fts5
```
I suspect this also fails for all the other virtual table modules (fts3, fts4, rtree) etc.

**Comment by neilotoole** [comment]
@Dialga: As of [`sq v0.42.0`](https://github.com/neilotoole/sq/releases/tag/v0.42.0), there is preliminary support for virtual tables and FTS5. See [docs](https://sq.io/docs/drivers/sqlite#extensions).

Can you give it a try? I'll leave this issue open for a little while if you want to give feedback.

Note that there is no special handling for FTS5 features in `sq`'s query language ("SLQ"), at least not yet. E.g. the `MATCH` mechanism is not exposed. I'm still not sure how best to proceed here... as a general rule, any SLQ feature should work across the supported backend databases. A generalized full-text-search construct in SLQ would need to map not only to SQLite FTS, but also to the equivalent mechanisms in Postgres, MySQL etc, but that's probably doable. 

But I haven't given any thought yet to how that would look like in SLQ, maybe something like:

```shell
$ sq '.actor | where (.first_name ~= "tom")'
```

I'd appreciate any thoughts you might have on it.

**Comment by Dialga** [comment]
Hi, thanks for adding this feature in, however I am not a heavy user of this particular way of querying FTS5 tables, hence I don't have any feedback on this. I only noticed and raised this error when I was testing `sq`.
