### ISSUE TITLE
sq driver --help

### ISSUE THREAD

**Issue by c-nv-s** [neilotoole/sq#414]
**Describe the bug**
run ``sq driver --help`` 
result is ``sq: unknown flag: --json`` 

**`sq` version**
"version": "v0.47.2",

**Comment by neilotoole** [comment]
@c-nv-s I'm not able to replicate this issue on the latest version, `v0.48.2`. Maybe it's a config interaction.

Can you please provide the output of `sq config ls -v`?

**Comment by c-nv-s** [comment]
so sorry, I checked my ``.bashrc`` file and saw this:
``alias sq='sq --json'``
