### ISSUE TITLE
Add a "saved queries" (archive) feature

### ISSUE THREAD

**Issue by neilotoole** [neilotoole/sq#46]
You should be able to archive queries for future use. For example:

```
> sq --archive=query1 '@my1.tbluser, @pg1.tbladdress | join(.uid) | .[0:100] | .uid, .email, .city, .zip'
> sq archive ls
NAME     SLQ
query1    @my1.tbluser, @pg1.tbladdress | join(.uid) | .[0:100] | .uid, .email, .city, .zip
> sq archive run query1
```
This could be implemented by having an `archive` section in `~/.sq/sq.yml`

**Comment by BaconIsAVeg** [comment]
I'd be happy if we could use pass queries in from a file/stdin.  Something like `cat file.sql | sq sql -`.
