### ISSUE TITLE
Two-letter driver names ('pg' instead of 'postgres')

### ISSUE THREAD

**Issue by neilotoole** [neilotoole/sq#54]
In keeping with `sq`'s general goal of terseness, `sq` should prefer short driver names. As in:

```
# Prefer this:
$sq add 'pg://user:pass@localhost/sakila`

# Over existing mechanism:
$ sq add 'postgres://user:pass@localhost/sakila'
```

Similarly `my` for `mysql`, `ms` for `sqlserver`/`mssql`, `sl` for `sqlite3`, etc. The `sq add` cmd should still accept the long variants, and `sq` should be able to read the long variants from config (e.g. if the user manually edits `sq.yml`).

**Comment by kobayashi** [comment]
Hello,

I have just added PR #93 for this. Please let me know if there is something to change or the other way.

**Comment by neilotoole** [comment]
After several looks into this, it's 👎.

Much of the pain has gone away due to implementation of `sq`'s excellent shell completion. But the main vote against this is that the connection string URLs would be non-canonical, making sense only to `sq`, but not to any other programs or libraries. It's not worth the pain.
