### ISSUE TITLE
MySQL driver options are stripped during "add"

### ISSUE THREAD

**Issue by macfisherman** [neilotoole/sq#90]
Trying to add a MySQL host with old passwords:

    sq add --handle=@segv 'mysql://user:password@host/database?allowOldPasswords=1'
    
    sq: failed to ping @segv [mysql://segv:****@segvdb/segv]: this user requires old password authentication. If you still want to use it, please add 'allowOldPasswords=1' to your DSN. See also https://github.com/go-sql-driver/mysql/wiki/old_passwords

Stepping through the code shows this line:
https://github.com/neilotoole/sq/blob/b7cb0a0b66a981e5c4d16b7f533eeb241d4c1f04/drivers/mysql/mysql.go#L410

resulting a dsn of:

    "user:password@tcp(host)/database"

It is possible that I'm misunderstanding how to add driver options.

**Comment by neilotoole** [comment]
@macfisherman This is a bug. Will look into. Thank you.

**Comment by neilotoole** [comment]
@macfisherman There's a fix for this, published in `sq v0.15.3`. Could you please verify, and re-open the issue if the problem is not fixed?

**Comment by macfisherman** [comment]
Verified:
    sq 0.15.3    #2d843c95    2021-03-13T17:13:06Z

    $ sq add --handle=@segv2 'mysql://user:password@host/db?allowOldPasswords=1'
    @segv2  mysql  user@host/db
    jeffs-mbp-2:research jeff$ sq ping 
    $ sq ping @segv2
    @segv2     298ms  pong

My local copy did the same change. I wasn't sure if that was the right approach, but it seems it was. Thanks again.
