### ISSUE TITLE
Adding a source with special characters in password

### ISSUE THREAD

**Issue by sunny0day** [neilotoole/sq#95]
Works:
`sq add 'sqlserver://test:test@localhost?database=x'`

Doesn't work:
`sq add 'sqlserver://test:test#@localhost?database=x'`
Error: sq: parse "sqlserver://test:test": invalid port ":test" after host

What's the recommended way to add a source in case the password contains special characters like `#`? Can a source be manually added, for example?

**Comment by sunny0day** [comment]
Additional notes:
- One can add a source manually via ~/.config/sq/sq.yml
- When manually added and using the source, the same error is shown (invalid port ... after host)

**Comment by sunny0day** [comment]
'Fixed' by manually converting the special characters to percent-encoding. See https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_the_percent_character

**Comment by neilotoole** [comment]
I should have closed this a while ago. See: https://sq.io/docs/cmd/add/#password-visibility
