### ISSUE TITLE
Auto Increment Duplicate Column name

### ISSUE THREAD

**Issue by StephaneTy-Pro** [neilotoole/sq#99]
When i use a xlsx file as an entry, and when thos file as duplicate header (line 1) , sq fail
Could you add an option to auto add an index behind the column, think it could complete your suggestion of https://github.com/neilotoole/sq/issues/15

**Comment by neilotoole** [comment]
@StephaneTy-Pro: This is finally [implemented](https://sq.io/docs/drivers/xlsx#duplicate-columns) as of [`v0.41.0`](https://github.com/neilotoole/sq/releases/tag/v0.41.0).
